<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Personal Knowledge');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?>
</head>
<body>
<p>Personal Knowledge</p>
<input size="100" type="text"/><input type="submit" value="search"/>
<div id="content">
<?php echo $this->layout()->content; ?>
</div>
<p>&nbsp;</p>
</body>
</html>